### ISSUE TITLE
为什么我这里只有一个地区的

### ISSUE THREAD

**Issue by xiaoxiaozhoutop** [tnnevol/ACL4SSR#2]
![屏幕截图 2024-09-11 150749](https://github.com/user-attachments/assets/5d16e6f7-3b68-410e-88bf-44fd19e3c10a)
只有一个地区的

**Comment by tnnevol** [comment]
可以截图一下手动切换里面的节点吗。
该规则只支持以下区域
![image](https://github.com/user-attachments/assets/182c4b1b-23b5-4564-b991-862679b0de26)

**Comment by xiaoxiaozhoutop** [comment]
> 可以截图一下手动切换里面的节点吗。 该规则只支持以下区域 ![图像](https://private-user-images.githubusercontent.com/28475939/367491639-182c4b1b-23b5-4564-b991-862679b0de26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3OTc0MzYsIm5iZiI6MTcyNjc5NzEzNiwicGF0aCI6Ii8yODQ3NTkzOS8zNjc0OTE2MzktMTgyYzRiMWItMjNiNS00NTY0LWI5OTEtODYyNjc5YjBkZTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDAxNTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4M2MxODY2MzMwNjU2NTZjZGZiODQyNzFhZWM3NjI4ZmFmZGY1MDk3NzZlOTBmNmQ3N2ViY2VlNDkzYTZlNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fQKuz8LIZlKm1P6RLjW5NNg8F5S2ZWcqAMmWnC_vp2E)

![image](https://github.com/user-attachments/assets/a108a600-2dee-4755-a3b4-7927cd552c50)
这个就是

**Comment by xiaoxiaozhoutop** [comment]
> 可以截图一下手动切换里面的节点吗。 该规则只支持以下区域 ![图像](https://private-user-images.githubusercontent.com/28475939/367491639-182c4b1b-23b5-4564-b991-862679b0de26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3OTc0MzYsIm5iZiI6MTcyNjc5NzEzNiwicGF0aCI6Ii8yODQ3NTkzOS8zNjc0OTE2MzktMTgyYzRiMWItMjNiNS00NTY0LWI5OTEtODYyNjc5YjBkZTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDAxNTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4M2MxODY2MzMwNjU2NTZjZGZiODQyNzFhZWM3NjI4ZmFmZGY1MDk3NzZlOTBmNmQ3N2ViY2VlNDkzYTZlNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fQKuz8LIZlKm1P6RLjW5NNg8F5S2ZWcqAMmWnC_vp2E)

![image](https://github.com/user-attachments/assets/d77e4d9c-2c32-4f14-8349-fa72606c83cc)
能不能增加以下地区

**Comment by tnnevol** [comment]
> > 可以截图一下手动切换里面的节点吗。 该规则只支持以下区域 ![图像](https://private-user-images.githubusercontent.com/28475939/367491639-182c4b1b-23b5-4564-b991-862679b0de26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3OTc0MzYsIm5iZiI6MTcyNjc5NzEzNiwicGF0aCI6Ii8yODQ3NTkzOS8zNjc0OTE2MzktMTgyYzRiMWItMjNiNS00NTY0LWI5OTEtODYyNjc5YjBkZTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDAxNTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4M2MxODY2MzMwNjU2NTZjZGZiODQyNzFhZWM3NjI4ZmFmZGY1MDk3NzZlOTBmNmQ3N2ViY2VlNDkzYTZlNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fQKuz8LIZlKm1P6RLjW5NNg8F5S2ZWcqAMmWnC_vp2E)
> 
> ![image](https://private-user-images.githubusercontent.com/103326597/369232295-d77e4d9c-2c32-4f14-8349-fa72606c83cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3OTgyNTksIm5iZiI6MTcyNjc5Nzk1OSwicGF0aCI6Ii8xMDMzMjY1OTcvMzY5MjMyMjk1LWQ3N2U0ZDljLTJjMzItNGYxNC04MzQ5LWZhNzI2MDZjODNjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQwMjA1NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDUzZjU2NGQyY2QyOGY1NDE4NzQ0NjAwNTYyYmVhOTA0NWY0OGMwMDQzNGRmNDU4OTI2ZGU3YWJlZTFlNTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fs2DVEhG46cf5cm0sw3-6ovsI7qYfvGySE8d0_AoJXY) 能不能增加以下地区

这是两个不同的机场的订阅吗

**Comment by tnnevol** [comment]
> > 可以截图一下手动切换里面的节点吗。 该规则只支持以下区域 ![图像](https://private-user-images.githubusercontent.com/28475939/367491639-182c4b1b-23b5-4564-b991-862679b0de26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3OTc0MzYsIm5iZiI6MTcyNjc5NzEzNiwicGF0aCI6Ii8yODQ3NTkzOS8zNjc0OTE2MzktMTgyYzRiMWItMjNiNS00NTY0LWI5OTEtODYyNjc5YjBkZTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDAxNTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4M2MxODY2MzMwNjU2NTZjZGZiODQyNzFhZWM3NjI4ZmFmZGY1MDk3NzZlOTBmNmQ3N2ViY2VlNDkzYTZlNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fQKuz8LIZlKm1P6RLjW5NNg8F5S2ZWcqAMmWnC_vp2E)
> 
> ![image](https://private-user-images.githubusercontent.com/103326597/369231591-a108a600-2dee-4755-a3b4-7927cd552c50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3OTg5NTEsIm5iZiI6MTcyNjc5ODY1MSwicGF0aCI6Ii8xMDMzMjY1OTcvMzY5MjMxNTkxLWExMDhhNjAwLTJkZWUtNDc1NS1hM2I0LTc5MjdjZDU1MmM1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQwMjE3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iN2M4MjlhNzQ1YjlhMmM3NjRjYzY3YTRhZjhiMjU5NDNhYjliY2EyY2NjYzk0YWI0YjZmYTZiOTY3YjlkYjFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gQ5tgc0eDjIt5dKfPxjbC7PwhPNlXoBRLXvsTfftjjE) 这个就是

增加了[日本和香港](https://github.com/tnnevol/ACL4SSR/commit/57510117a986967d5dba32d28582c40dd530959b)正则，[脚本](https://github.com/tnnevol/ACL4SSR/raw/refs/heads/master/ClashVerge/dist/ACL4SSR_Online_Full.js)已更新

**Comment by xiaoxiaozhoutop** [comment]
> > > 可以截图一下手动切换里面的节点吗。 该规则只支持以下区域 ![图像](https://private-user-images.githubusercontent.com/28475939/367491639-182c4b1b-23b5-4564-b991-862679b0de26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3OTc0MzYsIm5iZiI6MTcyNjc5NzEzNiwicGF0aCI6Ii8yODQ3NTkzOS8zNjc0OTE2MzktMTgyYzRiMWItMjNiNS00NTY0LWI5OTEtODYyNjc5YjBkZTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDAxNTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4M2MxODY2MzMwNjU2NTZjZGZiODQyNzFhZWM3NjI4ZmFmZGY1MDk3NzZlOTBmNmQ3N2ViY2VlNDkzYTZlNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fQKuz8LIZlKm1P6RLjW5NNg8F5S2ZWcqAMmWnC_vp2E)
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/103326597/369232295-d77e4d9c-2c32-4f14-8349-fa72606c83cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3OTgyNTksIm5iZiI6MTcyNjc5Nzk1OSwicGF0aCI6Ii8xMDMzMjY1OTcvMzY5MjMyMjk1LWQ3N2U0ZDljLTJjMzItNGYxNC04MzQ5LWZhNzI2MDZjODNjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQwMjA1NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDUzZjU2NGQyY2QyOGY1NDE4NzQ0NjAwNTYyYmVhOTA0NWY0OGMwMDQzNGRmNDU4OTI2ZGU3YWJlZTFlNTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fs2DVEhG46cf5cm0sw3-6ovsI7qYfvGySE8d0_AoJXY) 能不能增加以下地区
> 
> 这是两个不同的机场的订阅吗

是的，前面那个没有美国和印度的

**Comment by xiaoxiaozhoutop** [comment]
> > > 可以截图一下手动切换里面的节点吗。 该规则只支持以下区域 ![图像](https://private-user-images.githubusercontent.com/28475939/367491639-182c4b1b-23b5-4564-b991-862679b0de26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3OTc0MzYsIm5iZiI6MTcyNjc5NzEzNiwicGF0aCI6Ii8yODQ3NTkzOS8zNjc0OTE2MzktMTgyYzRiMWItMjNiNS00NTY0LWI5OTEtODYyNjc5YjBkZTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDAxNTIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4M2MxODY2MzMwNjU2NTZjZGZiODQyNzFhZWM3NjI4ZmFmZGY1MDk3NzZlOTBmNmQ3N2ViY2VlNDkzYTZlNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fQKuz8LIZlKm1P6RLjW5NNg8F5S2ZWcqAMmWnC_vp2E)
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/103326597/369232295-d77e4d9c-2c32-4f14-8349-fa72606c83cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3OTgyNTksIm5iZiI6MTcyNjc5Nzk1OSwicGF0aCI6Ii8xMDMzMjY1OTcvMzY5MjMyMjk1LWQ3N2U0ZDljLTJjMzItNGYxNC04MzQ5LWZhNzI2MDZjODNjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQwMjA1NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDUzZjU2NGQyY2QyOGY1NDE4NzQ0NjAwNTYyYmVhOTA0NWY0OGMwMDQzNGRmNDU4OTI2ZGU3YWJlZTFlNTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fs2DVEhG46cf5cm0sw3-6ovsI7qYfvGySE8d0_AoJXY) 能不能增加以下地区
> 
> 这是两个不同的机场的订阅吗

是的，前面那个没有美国和印度的

**Comment by MinanaYaa** [comment]
我是一个地区都不显示

**Comment by xiaoxiaozhoutop** [comment]
能否参考：https://github.com/Aethersailor/Custom_Clash_Rules/blob/main/cfg/Custom_Clash_Full.ini  更新一下
