### ISSUE TITLE
地区都不显示是因为节点前面有图标吗

### ISSUE THREAD

**Issue by MinanaYaa** [tnnevol/ACL4SSR#3]
![图片](https://github.com/user-attachments/assets/d6911258-25dc-4325-a0b3-d23205b75cbf)

**Comment by tnnevol** [comment]
不应该呀，我这边是有标注英文正则的

**Comment by MinanaYaa** [comment]
> 不应该呀，我这边是有标注英文正则的

应该是因为用了集合订阅，正则匹配的时候节点还没解析，也不知道咋弄了
